# we will use some special secret in our repo, called GITHUB_TOKEN, that doest required to be added on our settings, and will allow us to authenticate.
name: Decrypt files

on:
  push:
    branches:
      - feature/*

jobs:
  decrypt-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
      - name: Decrypt
        env:
          PASSPHRASE: ${{ secrets.SENSITIVE_INFO_PASS }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/sensitive_info.json sensitive_info.json.gpg
      - name: Print our file content
        run: cat $HOME/sensitive_info.json
